version: '3'

services:

  #React Nextjs Node Service

  node:

    image: webskittersdocker/nvmnode20:latest

    container_name: superior-fence-ui-AstroJS

    restart: unless-stopped

    working_dir: /home/wtsadmin/myapp

    
    volumes:

      - ./:/home/wtsadmin/myapp

    ports:

      - "14258:14258"
    command: >
      sh -c "yarn run preview"


#Docker Networks

networks:
  default:
    external:
      name: webskitters