dev-deployment:
 variables:
   GIT_STRATEGY: fetch
 script:
   - bash ~/gitlab/astro/astrojs-projectdeploy-yarn-v1.sh
 environment:
     name: Development
     url : https://superior-fence-ui.dedicateddevelopers.us/
 tags:
   - node-nextjs2
 only:
   - dev
