export default {
  logo: "/assets/images/SFR-logo.png",
  footerLogo: "/assets/images/footerLogo.webp",
  spouImg1: "/assets/images/spouImg1.webp",
  prepareImg: "/assets/images/prepareImg.webp",
  prepareImg2: "/assets/images/prepareImg2.png",
  prepareImg3: "/assets/images/prepareImg3.png",
  prepareImg4: "/assets/images/prepareImg4.png",
  prepareImg5: "/assets/images/prepareImg5.png",
  fence: "/assets/images/fence.webp",
  star_rating: "/assets/images/star_rating.png",
  bg_block: "/assets/images/bg_block.png",
  FenceShadow: "/assets/images/Fence-Shadow.png",
  fenceSecBg: "/assets/images/fenceSecBg.png",
  newsRcntPostImg1: "/assets/images/newsRcntPostImg1.webp",
  newsRcntPostImg2: "/assets/images/newsRcntPostImg2.webp",
  newsRcntPostImg3: "/assets/images/newsRcntPostImg3.webp",
  newsRcntPostImg4: "/assets/images/newsRcntPostImg4.webp",
  newsRcntPostImg5: "/assets/images/newsRcntPostImg5.webp",
  newsRcntPostImg6: "/assets/images/newsRcntPostImg6.webp",
  newsRcntPostImg7: "/assets/images/newsRcntPostImg7.webp",
  newsRcntPostImg8: "/assets/images/newsRcntPostImg8.webp",
  newsRcntPostImg9: "/assets/images/newsRcntPostImg9.webp",
  newsRcntPostImg10: "/assets/images/newsRcntPostImg10.webp",
  newsRcntPostImg11: "/assets/images/newsRcntPostImg11.webp",
  newsRcntPostImg13: "/assets/images/newsRcntPostImg13.webp",
  newsRcntPostImg14: "/assets/images/newsRcntPostImg14.webp",
  newsRcntPostImg15: "/assets/images/newsRcntPostImg15.webp",
  newsRcntPostImg16: "/assets/images/newsRcntPostImg16.webp",
  newsRcntPostImg17: "/assets/images/newsRcntPostImg17.webp",
  newsRcntPostImg18: "/assets/images/newsRcntPostImg18.webp",
  fence_banner_img: "/assets/images/fence_banner_img.jpg",
  starrating: "/assets/images/star_rating.png",
  badge: "/assets/images/badge.png",
  prepareImg6: "/assets/images/prepareImg6.webp",
  mapsec: "/assets/images/mapsec.png",
  location_marker: "/assets/images/location_marker.png",
  expand: "/assets/images/expand.png",
  fence1: "/assets/images/fence1.webp",
  blogDetailsImg1: "/assets/images/blogDetailsImg1.webp",
  blogDetailsBanner: "/assets/images/blogDetailsBanner.jpg",
  blogdetails2: "/assets/images/blogdetails2.jpg",
  placeholder: "/assets/images/placeholder.png",
  fence2: "/assets/images/fence2.webp",
  fence3: "/assets/images/fence3.webp",
  fence4: "/assets/images/fence4.webp",
  fence5: "/assets/images/fence5.webp",
  fence6: "/assets/images/fence6.webp",
  fence7: "/assets/images/fence7.webp",
  fence8: "/assets/images/fence8.webp",
  fence9: "/assets/images/fence9.webp",
  fence10: "/assets/images/fence10.webp",
  fence11: "/assets/images/fence11.webp",
  fence12: "/assets/images/fence12.webp",
  fence15: "/assets/images/fence15.webp",
  vinyl1: "/assets/images/vinyl1.webp",
  vinyl_fence1: "/assets/images/vinyl_fence1.jpg",
  vinyl_fence2: "/assets/images/vinyl_fence2.jpg",
  vinyl_fence3: "/assets/images/vinyl_fence3.jpg",
  vinyl_fence4: "/assets/images/vinyl_fence4.jpg",
  vinyl_fence5: "/assets/images/vinyl_fence5.jpg",
  vinyl_fence6: "/assets/images/vinyl_fence6.jpg",
  vinyl_fence7: "/assets/images/vinyl_fence7.jpg",
  vinyl_fence8: "/assets/images/vinyl_fence8.jpg",
  vinyl_fence9: "/assets/images/vinyl_fence9.jpg",
  innovation1: "/assets/images/innovation1.webp",
  innovation2: "/assets/images/innovation2.webp",
  innovation3: "/assets/images/innovation3.webp",
  innovation4: "/assets/images/innovation4.webp",
  pdfImg: "/assets/images/pdfImg.webp",
  about1: "/assets/images/about1.webp",
  about2: "/assets/images/about2.webp",
  about3: "/assets/images/about3.webp",
  about4: "/assets/images/about4.webp",
  faqsecimg: "/assets/images/faqsecimg.webp",
  thumb1: "/assets/images/thumb1.webp",
  contact1: "/assets/images/contact1.webp",
  facebook: "/assets/images/facebook.png",
  linkedin: "/assets/images/linkedin.png",
  twitter: "/assets/images/twitter.png",
  Testimonial_BG: "/assets/images/Testimonial_BG.png",
  mesgIcon: "/assets/images/mesgIcon.png",


  // SFRV2

  logoV2:"/assets/images/logoV2.png",
  mobilev2:"/assets/images/mobilev2.png",
  bannerv2:"/assets/images/bannerv2.png",
  ticksvg:"/assets/images/ticksvg.svg",
  fence_types:"/assets/images/fence-types.png",
  leftArrow:"/assets/images/leftArrow.svg",
  rightArrow:"/assets/images/rightArrow.svg",
  testimonialBack:"/assets/images/testimonialBack.png",
  footer_logo:"/assets/images/footer_logo.png",
  get1:"/assets/images/get1.png",
  get2:"/assets/images/get2.png",
  get3:"/assets/images/get3.png",
  stickerIcon:"/assets/images/stickerIcon.png",
};
