import { useState } from "react";
export const locationListData = [
  "Alachua",
  "Altamonte Springs",
  "Anna Maria",
  "Apalachicola",
  "Apopka",
  "Auburndale",
  "Atlantic Beach",
  "Aventura",
  "Babcock Ranch",
  "Bal Harbour",
  "Bartow",
  "Bay Harbor Islands",
  "Belle Meade",
  "Belleair",
  "Boca Raton",
  "Boise",
  "Bonita Springs",
  "Boynton Beach",
  "Bradenton",
  "Bradenton Beach",
  "Brandon",
  "Brentwood",
  "Cape Canaveral",
  "Cape Coral",
  "Carrollton",
  "Casselberry",
  "Celebration",
  "Chipley",
  "Cinnamon Cove",
  "Cinco Bayou",
  "Citrus Park",
  "Clermont",
  "Clearwater",
  "Cocoa",
  "Cocoa Beach",
  "Coconut Creek",
  "Conway",
  "Coral Gables",
  "Coral Springs",
  "Dade City",
  "Dania Beach",
  "Daphne",
  "Davenport",
  "Davie",
  "Daytona Beach",
  "DeBary",
  "DeFuniak Springs",
  "DeLand",
  "Delray Beach",
  "Deltona",
  "Destin",
  "Deerfield Beach",
  "Durham",
  "Dunedin",
  "Eagle",
  "Eagle Lake",
  "Edgewater",
  "Edgewood",
  "Englewood",
  "Eustis",
  "Fellsmere",
  "Fernandina Beach",
  "Fort Lauderdale",
  "Fort Meade",
  "Fort Myers",
  "Fort Myers Beach",
  "Fort Pierce",
  "Forest Hills",
  "Franklin",
  "Fruitland Park",
  "Fuquay Varina",
  "Gainesville",
  "Garner",
  "Gateway",
  "Green Cove Springs",
  "Greenacres",
  "Gulf Breeze",
  "Gulfport",
  "Haines City",
  "Hallandale Beach",
  "Hastings",
  "Hawthorne",
  "Hendersonville",
  "Hialeah",
  "Hialeah Gardens",
  "Highland Beach",
  "Hobe Sound",
  "Holly Hill",
  "Holly Springs",
  "Holmes Beach",
  "Homestead",
  "Hutchinson Island",
  "Hypoluxo",
  "Indian River County",
  "Indian River Shores",
  "Indiantown",
  "Indialantic",
  "Jacksonville",
  "Jacksonville Beach",
  "Jensen Beach",
  "Juno Beach",
  "Jupiter",
  "Kissimmee",
  "Key Biscayne",
  "Kuna",
  "Lady Lake",
  "Lake Alfred",
  "Lake Buena Vista",
  "Lake Helen",
  "Lake Mary",
  "Lake Park",
  "Lake Wales",
  "Lake Worth",
  "Lakeland",
  "Land O’ Lakes",
  "Lauderdale-by-the-Sea",
  "Lauderhill",
  "La Vergne",
  "Leesburg",
  "Lehigh Acres",
  "Lighthouse Point",
  "Longboat Key",
  "Longwood",
  "Lutz",
  "Macclenny",
  "Madison",
  "Maitland",
  "Marco Island",
  "Margate",
  "Martin County",
  "McMinnville",
  "Melbourne",
  "Melbourne Beach",
  "Meridian",
  "Merritt Island",
  "Middleburg",
  "Middleton",
  "Milton",
  "Minneola",
  "Miramar",
  "Mount Dora",
  "Mount Juliet",
  "Murfreesboro",
  "Naples",
  "Nashville",
  "Neptune Beach",
  "New Port Richey",
  "New Smyrna Beach",
  "Niceville",
  "Nolensville",
  "North Miami",
  "North Miami Beach",
  "North Port",
  "Oak Hill",
  "Oakland Park",
  "Ocala",
  "Ocean Ridge",
  "Ocoee",
  "Oldsmar",
  "Orchid",
  "Orange City",
  "Orange Park",
  "Orlando",
  "Ormond Beach",
  "Osprey",
  "Oviedo",
  "Palm Bay",
  "Palm Beach",
  "Palm Beach Gardens",
  "Palm Coast",
  "Palmetto",
  "Panama City",
  "Panama City Beach",
  "Pembroke Pines",
  "Pensacola",
  "Pine Island",
  "Pinecrest",
  "Pinellas Park",
  "Plant City",
  "Plantation",
  "Poinciana",
  "Pompano Beach",
  "Ponte Vedra Beach",
  "Port Orange",
  "Port Richey",
  "Port Saint Lucie",
  "Port Salerno",
  "Punta Gorda",
  "Raleigh",
  "River Park",
  "Rockledge",
  "Rolesville",
  "Royal Palm Beach",
  "Safety Harbor",
  "San Antonio",
  "Sanibel",
  "Sanford",
  "Satellite Beach",
  "Sebastian",
  "Seaside",
  "Shalimar",
  "Smyrna",
  "Spring Hill",
  "Star",
  "St. Augustine",
  "St. Augustine Beach",
  "St. Cloud",
  "St. Petersburg",
  "Stuart",
  "Surfside",
  "Sweetwater",
  "Tallahassee",
  "Tamarac",
  "Tarpon Springs",
  "Tavares",
  "Temple Terrace",
  "Titusville",
  "Treasure Island",
  "Valparaiso",
  "Venice",
  "Vero Beach",
  "Wake Forest",
  "Wellington",
  "Wesley Chapel",
  "West Melbourne",
  "West Palm Beach",
  "Weston",
  "White City",
  "Wilton Manors",
  "Windermere",
  "Winter Garden",
  "Winter Haven",
  "Winter Park",
  "Winter Springs",
  "Yulee",
  "Zephyrhills",
];

export default function FooterList() {
  const [listShow, setListShow] = useState(false);
  const handelShow = () => {
    setListShow(!listShow);
  };
  return (
    <div className="bg-[#dddddd] py-[24px]">
      <div className="container">
        <div className="">
          <button
            type="button"
            onClick={handelShow}
            className={
              listShow
                ? "text-primary flex justify-between w-full font-montserratsemibold text-[14px]"
                : "text-[14px] text-headingPrimary flex justify-between w-full font-montserratsemibold hover:text-primary"
            }
          >
            We proudly serve many cities and counties throughout the Country.
            Click to see all our locations.{" "}
            {listShow ? <span>-</span> : <span>+</span>}
          </button>
        </div>
        {listShow ? (
          <div className="mt-[60px] pt-[20px] border-solid border-[#ccc] border-t-[1px]">
            <ul>
              {locationListData.map((items, index) => (
                <li key={index} className="mb-[6px]">
                  <a
                    href="#url"
                    className="text-base font-[14px] text-[#252525] flex justify-between w-full hover:text-[#821302]"
                  >
                    {items}
                  </a>
                </li>
              ))}
            </ul>
          </div>
        ) : null}
      </div>
    </div>
  );
}
